name: Scrape & update sheet

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          GSERVICE_KEY: ${{ secrets.GSERVICE_KEY }}
          SHEET_ID:     ${{ secrets.SHEET_ID }}
